### ISSUE TITLE
Can you add support for stm32duino board

### ISSUE THREAD

**Issue by qinglong1224** [PowerBroker2/SerialTransfer#13] opened 2020-03-26 08:38 UTC
Hello ,
       Can you add support for stm32duino board?

**Comment by PowerBroker2** [comment] 2020-03-26 18:16
What problems are you having with the stm32duino board in terms of this library? Is it a compile-time error or runtime-error?

**Comment by PowerBroker2** [comment] 2020-03-26 20:37
This should be fixed in [release 1.3.0](https://github.com/PowerBroker2/SerialTransfer/releases/tag/1.3.0).

**Comment by PowerBroker2** [comment] 2020-03-28 22:36
Due to lack of response from OP I'm assuming the issue is resolved and am closing this issue.

**Closed as completed by PowerBroker2** 2020-03-28 22:36 UTC
Labels: enhancement
